### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nfsdaemon** [firolino/clang-tool#1]
> clang-tool/build$make
Scanning dependencies of target clang-tool
[ 11%] Building CXX object src/CMakeFiles/clang-tool.dir/main.cc.o
[ 22%] Building CXX object src/CMakeFiles/clang-tool.dir/utils/utils.cc.o
/var/tmp/clang/clang-tool/src/utils/utils.cc: In function 'bool utils::customRunToolOnCodeWithArgs(clang::FrontendAction*, const llvm::Twine&, const std::vector<std::__cxx11::basic_string<char> >&, const llvm::Twine&, const FileContentMappings&)':
/var/tmp/clang/clang-tool/src/utils/utils.cc:28:116: error: no matching function for call to 'clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char> >, clang::FrontendAction*&, clang::FileManager*)'
   28 |     clang::tooling::ToolInvocation invocation(getSyntaxOnlyToolArgs(args, fileNameRef), frontendAction, files.get());
      |                                                                                                                    ^
In file included from /var/tmp/clang/clang-tool/src/utils/utils.h:11,
                 from /var/tmp/clang/clang-tool/src/utils/utils.cc:1:
/usr/lib/llvm/11/include/clang/Tooling/Tooling.h:257:3: note: candidate: 'clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char> >, clang::tooling::ToolAction*, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>)'
  257 |   ToolInvocation(std::vector<std::string> CommandLine, ToolAction *Action,
      |   ^~~~~~~~~~~~~~
/usr/lib/llvm/11/include/clang/Tooling/Tooling.h:257:3: note:   candidate expects 4 arguments, 3 provided
/usr/lib/llvm/11/include/clang/Tooling/Tooling.h:245:3: note: candidate: 'clang::tooling::ToolInvocation::ToolInvocation(std::vector<std::__cxx11::basic_string<char> >, std::unique_ptr<clang::FrontendAction>, clang::FileManager*, std::shared_ptr<clang::PCHContainerOperations>)'
  245 |   ToolInvocation(std::vector<std::string> CommandLine,
      |   ^~~~~~~~~~~~~~
/usr/lib/llvm/11/include/clang/Tooling/Tooling.h:246:50: note:   no known conversion for argument 2 from 'clang::FrontendAction*' to 'std::unique_ptr<clang::FrontendAction>'
  246 |                  std::unique_ptr<FrontendAction> FAction, FileManager *Files,
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/usr/lib/llvm/11/include/clang/Tooling/Tooling.h:232:7: note: candidate: 'clang::tooling::ToolInvocation::ToolInvocation(const clang::tooling::ToolInvocation&)'
  232 | class ToolInvocation {
      |       ^~~~~~~~~~~~~~
/usr/lib/llvm/11/include/clang/Tooling/Tooling.h:232:7: note:   candidate expects 1 argument, 3 provided
make[2]: *** [src/CMakeFiles/clang-tool.dir/build.make:122: src/CMakeFiles/clang-tool.dir/utils/utils.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: src/CMakeFiles/clang-tool.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

Hello I tried to build your project but I reached an error.
Is there easy way to fix it?
I understand that a year and a half has passed since the publication and the clang api has changed, but still I cannot fix the error myself.

**Comment by firolino** [comment]
Hi,
thanks for reporting the issue. I just uploaded the fix for newer clang versions. Could you try building it again?
